### ISSUE TITLE
Peer to peer code Review

### ISSUE THREAD

**Issue by Cathella** [adewaleK/Design-Tear-Down#1]

**Comment by ricardo123321** [comment]
the .middle_container can be a grid for easier maleability

**Comment by ricardo123321** [comment]
for easy avoidance of the possible horizontal scroll add a box size: border box to the * element

**Comment by ricardo123321** [comment]
don't forget to add this
![Uploading www.smashingmagazine.com_.png…]()

**Comment by hemantso** [comment]
- make the color combination more attractive
- there should be some gap between two different section
- add more content in website ( increase the vertical content) as the original site
-logo and button should be in the same line

**Comment by ricardo123321** [comment]
![www smashingmagazine com_](https://user-images.githubusercontent.com/60460371/76531514-b4640500-644b-11ea-8c75-e71daa2fb400.png)

**Comment by LoboArkano** [comment]
You don't need to add any image. Just create a box with a background.

**Comment by Cathella** [comment]
Okay, team thanks!
